[build]
  publish = "."
  command = "echo 'No build process needed for static site'"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirect rules
[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 301

[[redirects]]
  from = "/polityka-prywatnosci"
  to = "/privacy.html"
  status = 301

# Forms configuration for Netlify Forms (backup option)
[build]
  functions = "netlify/functions"

# Environment variables (these will be set in Netlify dashboard)
# FIREBASE_API_KEY
# FIREBASE_AUTH_DOMAIN
# FIREBASE_PROJECT_ID
# FIREBASE_STORAGE_BUCKET
# FIREBASE_MESSAGING_SENDER_ID
# FIREBASE_APP_ID
# GA_MEASUREMENT_ID